<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?php echo $this->__('Reindex Management')?></h3></td>			
            <td class="a-right">
                <button onclick="editForm.submit()" class="scalable save" type="button"><span>Run</span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
<?php
$indexs = $this->getAllIndexs();
$stores = Mage::app()->getStores();
?>
<div id="__fieldmapping" style="">
    <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Field Mapping')?></h4>
    </div>
    <form id="edit_form" name="edit_form" method="post" action="<?php echo $this->getUrl('*/*/post')?>" enctype="multipart/form-data">
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">			
                <tr>
                    <td>
						<select name="index" style="width:250px;" >
							<option value=""><?php echo $this->__('Select Index') ?></option>
							<?php foreach ($indexs  as $id => $name) : ?>
								<option value="<?php echo $id ?>"><?php echo $name ?></option>
							<?php endforeach; ?>
						</select>
					</td>
                    <td>
						<--> 
					</td>
					<td>
						<select name="store" style="width:250px;" >
							<option value=""><?php echo $this->__('Select Enable Store') ?></option>
							<?php foreach ($stores  as $store) : ?>
                                <?php if($store->getIsActive()): ?>
								    <option value="<?php echo $store->getId() ?>"><?php echo $store->getName() ?></option>
                                <?php endif; ?>
							<?php endforeach; ?>
						</select>
					</td>
                </tr>			
            </table>
        </fieldset>
    </form>
</div>
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>